# Generated by Django 5.1.4 on 2025-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='codigo_correlativo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
