# Generated by Django 5.1.4 on 2025-11-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0002_solicitudcompra_codigo_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosolicitud',
            name='caracteristica_especial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
