# Generated by Django 5.1.4 on 2025-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0003_insumosolicitud_caracteristica_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosolicitud',
            name='renglon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
