# Generated by Django 5.1.4 on 2025-11-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0005_servicio_serviciosolicitud'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviciosolicitud',
            unique_together=set(),
        ),
    ]
