# Generated by Django 5.1.4 on 2025-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0006_alter_serviciosolicitud_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='caracteristica_especial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
