# Generated by Django 5.1.4 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0007_servicio_caracteristica_especial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='card_images/')),
            ],
            options={
                'db_table': 'empleados_app_empleado',
                'managed': False,
            },
        ),
    ]
