# Generated by Django 5.1.4 on 2025-12-17 20:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0008_empleado"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresupuestoAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField(unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="CDP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RESERVADO", "Reservado"),
                            ("EJECUTADO", "Ejecutado"),
                            ("LIBERADO", "Liberado"),
                        ],
                        default="RESERVADO",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cdps",
                        to="scompras_app.solicitudcompra",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="CDO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cdp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cdo",
                        to="scompras_app.cdp",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="PresupuestoRenglon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_renglon", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("monto_inicial", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "monto_modificado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "monto_reservado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "monto_ejecutado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "presupuesto_anual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renglones",
                        to="scompras_app.presupuestoanual",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo_renglon"],
                "unique_together": {("presupuesto_anual", "codigo_renglon")},
            },
        ),
        migrations.CreateModel(
            name="KardexPresupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("CARGA_INICIAL", "Carga inicial"),
                            ("TRANSFERENCIA_SALIDA", "Transferencia salida"),
                            ("TRANSFERENCIA_ENTRADA", "Transferencia entrada"),
                            ("CDP_RESERVA", "Creación de CDP"),
                            ("CDP_LIBERACION", "Liberación de CDP"),
                            ("EJECUCION", "Ejecución presupuestaria"),
                        ],
                        max_length=50,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("saldo_nuevo", models.DecimalField(decimal_places=2, max_digits=14)),
                ("referencia", models.CharField(max_length=255)),
                (
                    "renglon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kardex",
                        to="scompras_app.presupuestorenglon",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddField(
            model_name="cdp",
            name="renglon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cdps",
                to="scompras_app.presupuestorenglon",
            ),
        ),
        migrations.CreateModel(
            name="TransferenciaPresupuestaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "presupuesto_anual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias",
                        to="scompras_app.presupuestoanual",
                    ),
                ),
                (
                    "renglon_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_entrada",
                        to="scompras_app.presupuestorenglon",
                    ),
                ),
                (
                    "renglon_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_salida",
                        to="scompras_app.presupuestorenglon",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
