# Generated by Django 5.1.4 on 2025-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0009_presupuestoanual_cdp_cdo_presupuestorenglon_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kardexpresupuesto",
            options={
                "ordering": ["-fecha", "-id"],
                "verbose_name": "Kardex presupuestario",
                "verbose_name_plural": "Kardex presupuestario",
            },
        ),
        migrations.RenameField(
            model_name="kardexpresupuesto",
            old_name="renglon",
            new_name="presupuesto_renglon",
        ),
        migrations.RemoveField(
            model_name="kardexpresupuesto",
            name="tipo_movimiento",
        ),
        migrations.AddField(
            model_name="kardexpresupuesto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CARGA_INICIAL", "Carga inicial"),
                    ("TRANSFERENCIA_SALIDA", "Transferencia salida"),
                    ("TRANSFERENCIA_ENTRADA", "Transferencia entrada"),
                    ("RESERVA_CDP", "Creación de CDP"),
                    ("LIBERACION_CDP", "Liberación de CDP"),
                    ("EJECUCION_CDP", "Ejecución presupuestaria"),
                ],
                default="CARGA_INICIAL",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presupuestoanual",
            name="activo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="kardexpresupuesto",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="kardexpresupuesto",
            name="referencia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
