# Generated by Django 5.1.4 on 2025-12-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0010_alter_kardexpresupuesto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kardexpresupuesto",
            name="solicitud",
            field=models.ForeignKey(
                blank=True,
                help_text="Referencia contable a la solicitud de compra vinculada (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos_kardex",
                to="scompras_app.solicitudcompra",
            ),
        ),
    ]
