# Generated by Django 5.1.4 on 2026-01-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0011_kardexpresupuesto_solicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="kardexpresupuesto",
            name="cdo",
            field=models.ForeignKey(
                blank=True,
                help_text="Referencia opcional al CDO asociado al movimiento.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kardex_movimientos",
                to="scompras_app.cdo",
            ),
        ),
        migrations.AddField(
            model_name="kardexpresupuesto",
            name="cdp",
            field=models.ForeignKey(
                blank=True,
                help_text="Referencia opcional al CDP asociado al movimiento.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kardex_movimientos",
                to="scompras_app.cdp",
            ),
        ),
        migrations.AddField(
            model_name="kardexpresupuesto",
            name="transferencia",
            field=models.ForeignKey(
                blank=True,
                help_text="Referencia opcional a la transferencia asociada al movimiento.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kardex_movimientos",
                to="scompras_app.transferenciapresupuestaria",
            ),
        ),
        migrations.CreateModel(
            name="SubproductoPresupuestoRenglon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "presupuesto_anual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_subproductos",
                        to="scompras_app.presupuestoanual",
                    ),
                ),
                (
                    "presupuesto_renglon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subproducto_renglones",
                        to="scompras_app.presupuestorenglon",
                    ),
                ),
                (
                    "subproducto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_presupuesto",
                        to="scompras_app.subproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de subproducto a renglón",
                "verbose_name_plural": "Asignaciones de subproductos a renglones",
                "unique_together": {
                    ("presupuesto_anual", "subproducto", "presupuesto_renglon")
                },
            },
        ),
    ]
