# Generated by Django 5.1.4 on 2026-01-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0012_kardexpresupuesto_cdo_kardexpresupuesto_cdp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuestorenglon",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scompras_app.producto",
            ),
        ),
        migrations.AddField(
            model_name="presupuestorenglon",
            name="subproducto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scompras_app.subproducto",
            ),
        ),
        migrations.DeleteModel(
            name="SubproductoPresupuestoRenglon",
        ),
    ]
