# Generated by Django 5.1.4 on 2026-01-13 14:54

from django.db import migrations, models
from django.db.models import Count


def verificar_duplicados(apps, schema_editor):
    PresupuestoRenglon = apps.get_model("scompras_app", "PresupuestoRenglon")
    duplicados = (
        PresupuestoRenglon.objects.values(
            "presupuesto_anual_id",
            "codigo_renglon",
            "producto_id",
            "subproducto_id",
        )
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    if not duplicados.exists():
        return

    conflictos = []
    for dup in duplicados:
        ids = list(
            PresupuestoRenglon.objects.filter(
                presupuesto_anual_id=dup["presupuesto_anual_id"],
                codigo_renglon=dup["codigo_renglon"],
                producto_id=dup["producto_id"],
                subproducto_id=dup["subproducto_id"],
            )
            .values_list("id", flat=True)
            .order_by("id")
        )
        conflictos.append(
            f"(presupuesto_anual={dup['presupuesto_anual_id']}, "
            f"codigo_renglon={dup['codigo_renglon']}, "
            f"producto_id={dup['producto_id']}, "
            f"subproducto_id={dup['subproducto_id']}) -> IDs {ids}"
        )

    raise RuntimeError(
        "Se encontraron renglones duplicados para la nueva restricción de unicidad. "
        "Revise y resuelva manualmente los siguientes conflictos antes de migrar:\n"
        + "\n".join(conflictos)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0013_presupuestorenglon_producto_and_more"),
    ]

    operations = [
        migrations.RunPython(verificar_duplicados, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="presupuestorenglon",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="presupuestorenglon",
            constraint=models.UniqueConstraint(
                fields=(
                    "presupuesto_anual",
                    "codigo_renglon",
                    "producto",
                    "subproducto",
                ),
                name="uniq_presupuesto_codigo_producto_subproducto",
            ),
        ),
    ]
