# Generated by Django 5.1.4 on 2026-01-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0014_alter_presupuestorenglon_unique_together_and_more'),
        ('scompras_app', '0014_subproductopresupuestorenglon'),
    ]

    operations = [
    ]
