# Generated by Django 5.1.4 on 2026-01-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0015_alter_presupuestorenglon_constraint_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="presupuestorenglon",
            name="uniq_pres_anual_prod_subprod_cod",
        ),
        migrations.AddConstraint(
            model_name="presupuestorenglon",
            constraint=models.UniqueConstraint(
                fields=(
                    "presupuesto_anual",
                    "producto",
                    "subproducto",
                    "codigo_renglon",
                ),
                name="uniq_renglon_por_producto_subproducto",
            ),
        ),
    ]
