# Generated by Django 5.1.4 on 2026-01-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0015_merge_20260113_0854'),
        ('scompras_app', '0016_rename_renglon_constraint'),
    ]

    operations = [
    ]
