# Generated by Django 5.1.4 on 2026-01-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0016_rename_renglon_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="seccion",
            name="firmante_cargo",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="seccion",
            name="firmante_nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
