# Generated by Django 5.1.4 on 2026-01-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0017_merge_20260113_1117'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='presupuestorenglon',
            name='uniq_renglon_por_producto_subproducto',
        ),
        migrations.AddConstraint(
            model_name='presupuestorenglon',
            constraint=models.UniqueConstraint(fields=('presupuesto_anual', 'codigo_renglon', 'producto', 'subproducto'), name='uniq_renglon_por_producto_subproducto'),
        ),
    ]
