# Generated by Django 5.1.4 on 2026-01-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0017_seccion_firmante'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubproductoPresupuestoRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignación de subproducto a renglón',
                'verbose_name_plural': 'Asignaciones de subproductos a renglones',
            },
        ),
        migrations.RemoveConstraint(
            model_name='presupuestorenglon',
            name='uniq_renglon_por_producto_subproducto',
        ),
        migrations.AddConstraint(
            model_name='presupuestorenglon',
            constraint=models.UniqueConstraint(fields=('presupuesto_anual', 'codigo_renglon', 'producto', 'subproducto'), name='uniq_renglon_por_producto_subproducto'),
        ),
        migrations.AddField(
            model_name='subproductopresupuestorenglon',
            name='presupuesto_anual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_subproductos', to='scompras_app.presupuestoanual'),
        ),
        migrations.AddField(
            model_name='subproductopresupuestorenglon',
            name='presupuesto_renglon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducto_renglones', to='scompras_app.presupuestorenglon'),
        ),
        migrations.AddField(
            model_name='subproductopresupuestorenglon',
            name='subproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_presupuesto', to='scompras_app.subproducto'),
        ),
        migrations.AlterUniqueTogether(
            name='subproductopresupuestorenglon',
            unique_together={('presupuesto_anual', 'subproducto', 'presupuesto_renglon')},
        ),
    ]
