# Generated by Django 5.1.4 on 2026-01-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0017_seccion_firmante'),
        ('scompras_app', '0018_remove_presupuestorenglon_uniq_renglon_por_producto_subproducto_and_more'),
    ]

    operations = [
    ]
