# Generated by Django 5.1.4 on 2026-01-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0018_subproductopresupuestorenglon_and_more'),
        ('scompras_app', '0019_merge_20260114_1900'),
    ]

    operations = [
    ]
