# Generated by Django 5.1.4 on 2026-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0020_merge_20260114_2058"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviciosolicitud",
            name="caracteristica_especial",
            field=models.TextField(blank=True, null=True),
        ),
    ]
