# Generated by Django 5.1.4 on 2026-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scompras_app", "0021_serviciosolicitud_caracteristica_especial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviciosolicitud",
            name="nombre_override",
            field=models.TextField(blank=True, null=True),
        ),
    ]
