# Generated by Django 5.1.4 on 2026-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scompras_app', '0027_create_compras_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='codigo_presentacion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
