# Generated by Django 5.1.4 on 2025-11-18 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados_app', '0002_alter_empleado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('instructor', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='diplomas_app.curso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='empleados_app.empleado')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('curso', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diploma', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='diplomas/')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('curso_empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='diplomas_app.cursoempleado')),
            ],
        ),
    ]
