# Generated by Django 5.1.4 on 2025-11-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=150)),
                ('firma', models.ImageField(help_text='Suba la firma en PNG con fondo transparente.', upload_to='firmas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='instructor',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default=2, help_text='Código del curso (5 dígitos).', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
