# Generated by Django 5.1.4 on 2025-11-18 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas_app', '0002_firma_remove_curso_instructor_curso_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='archivo_pdf',
        ),
        migrations.AddField(
            model_name='curso',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='diplomas_app.firma'),
        ),
    ]
