# Generated by Django 5.1.4 on 2025-11-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas_app', '0003_remove_diploma_archivo_pdf_curso_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='firma',
        ),
        migrations.AddField(
            model_name='curso',
            name='firmas',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='diplomas_app.firma'),
        ),
    ]
