# Generated by Django 5.1.4 on 2025-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas_app', '0004_remove_curso_firma_curso_firmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='posiciones',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
