# Generated by Django 5.1.4 on 2026-03-17 18:13

import django.db.models.deletion
from django.db import migrations, models


def migrar_posiciones_a_disenos(apps, schema_editor):
    Curso = apps.get_model('diplomas_app', 'Curso')
    DisenoDiploma = apps.get_model('diplomas_app', 'DisenoDiploma')

    for curso in Curso.objects.all():
        if curso.diseno_diploma_id:
            continue

        nombre_diseno = f"Diseño migrado {curso.codigo}"
        estilos = curso.posiciones if isinstance(curso.posiciones, dict) else {}

        diseno = DisenoDiploma.objects.create(
            nombre=nombre_diseno,
            descripcion=f"Diseño creado automáticamente desde el curso {curso.codigo}.",
            estilos=estilos,
            activo=True,
        )
        curso.diseno_diploma_id = diseno.id
        curso.save(update_fields=['diseno_diploma'])


def reversa_migracion_posiciones(apps, schema_editor):
    Curso = apps.get_model('diplomas_app', 'Curso')

    for curso in Curso.objects.select_related('diseno_diploma').all():
        if curso.diseno_diploma_id and curso.diseno_diploma and not curso.posiciones:
            curso.posiciones = curso.diseno_diploma.estilos or {}
            curso.save(update_fields=['posiciones'])


class Migration(migrations.Migration):

    dependencies = [
        ("diplomas_app", "0005_curso_posiciones"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisenoDiploma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "imagen_fondo",
                    models.ImageField(
                        blank=True, null=True, upload_to="diplomas/fondos/"
                    ),
                ),
                ("estilos", models.JSONField(blank=True, default=dict)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Diseño de diploma",
                "verbose_name_plural": "Diseños de diploma",
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="diseno_diploma",
            field=models.ForeignKey(
                blank=True,
                help_text="Diseño de diploma que utilizará el curso.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="diplomas_app.disenodiploma",
            ),
        ),
        migrations.RunPython(migrar_posiciones_a_disenos, reversa_migracion_posiciones),
    ]
