# Generated by Django 5.1.4 on 2026-03-23 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_location_and_groups(apps, schema_editor):
    UbicacionDiploma = apps.get_model("diplomas_app", "UbicacionDiploma")
    Curso = apps.get_model("diplomas_app", "Curso")
    Firma = apps.get_model("diplomas_app", "Firma")
    DisenoDiploma = apps.get_model("diplomas_app", "DisenoDiploma")
    Group = apps.get_model("auth", "Group")

    ubicacion, _ = UbicacionDiploma.objects.get_or_create(
        nombre="General",
        defaults={
            "descripcion": "Ubicación general creada automáticamente para migrar registros existentes del módulo de Diplomas.",
            "activa": True,
        },
    )

    Curso.objects.filter(ubicacion__isnull=True).update(ubicacion=ubicacion)
    Firma.objects.filter(ubicacion__isnull=True).update(ubicacion=ubicacion)
    DisenoDiploma.objects.filter(ubicacion__isnull=True).update(ubicacion=ubicacion)

    Group.objects.get_or_create(name="Diplomas")
    Group.objects.get_or_create(name="Gestor_Diplomas")


def reverse_seed_default_location_and_groups(apps, schema_editor):
    UbicacionDiploma = apps.get_model("diplomas_app", "UbicacionDiploma")
    Curso = apps.get_model("diplomas_app", "Curso")
    Firma = apps.get_model("diplomas_app", "Firma")
    DisenoDiploma = apps.get_model("diplomas_app", "DisenoDiploma")
    try:
        ubicacion = UbicacionDiploma.objects.get(nombre="General")
    except UbicacionDiploma.DoesNotExist:
        return

    Curso.objects.filter(ubicacion=ubicacion).update(ubicacion=None)
    Firma.objects.filter(ubicacion=ubicacion).update(ubicacion=None)
    DisenoDiploma.objects.filter(ubicacion=ubicacion).update(ubicacion=None)


class Migration(migrations.Migration):

    dependencies = [
        ("diplomas_app", "0006_disenodiploma_curso_diseno_diploma"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UbicacionDiploma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ubicaciones_diplomas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de diplomas",
                "verbose_name_plural": "Ubicaciones de diplomas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cursos",
                to="diplomas_app.ubicaciondiploma",
            ),
        ),
        migrations.AddField(
            model_name="disenodiploma",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disenos",
                to="diplomas_app.ubicaciondiploma",
            ),
        ),
        migrations.AddField(
            model_name="firma",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="firmas",
                to="diplomas_app.ubicaciondiploma",
            ),
        ),
        migrations.CreateModel(
            name="UsuarioUbicacionDiploma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "asignado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones_ubicacion_diplomas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_usuarios",
                        to="diplomas_app.ubicaciondiploma",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignacion_ubicacion_diplomas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de usuario a ubicación",
                "verbose_name_plural": "Asignaciones de usuarios a ubicación",
            },
        ),
        migrations.RunPython(seed_default_location_and_groups, reverse_seed_default_location_and_groups),
    ]
