# Generated by Django 5.1.4 on 2026-03-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diplomas_app", "0007_ubicaciondiploma_curso_ubicacion_and_more"),
        ("empleados_app", "0004_alter_datosbasicosempleado_grupo_etnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursoempleado",
            name="observaciones",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_correo",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_dpi",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="diplomas/participantes/"
            ),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_nombre",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="cursoempleado",
            name="participante_telefono",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="cursoempleado",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="empleados_app.empleado",
            ),
        ),
    ]
