# Generated by Django 5.1.4 on 2026-08-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empleados_app", "0005_contrato_estado_contrato_fecha_registro_rescision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpedienteEmpleado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("estado", models.CharField(choices=[("pendiente", "Pendiente"), ("revision", "En revisión"), ("completo", "Completo")], default="pendiente", max_length=12)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expedientes_rrhh_actualizados", to=settings.AUTH_USER_MODEL)),
                ("empleado", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="expediente_rrhh", to="empleados_app.empleado")),
            ],
            options={
                "verbose_name": "expediente de empleado",
                "verbose_name_plural": "expedientes de empleados",
                "permissions": [("view_gestion_empleados", "Puede ver Gestión de Empleados"), ("manage_preselection", "Puede gestionar preselección"), ("review_employee_files", "Puede revisar expedientes"), ("edit_employee_record", "Puede editar la ficha del empleado"), ("manage_employee_contracts", "Puede gestionar contratos"), ("rescind_employee_contracts", "Puede rescindir contratos"), ("view_contract_information", "Puede consultar información contractual")],
            },
        ),
    ]
