import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_catalogos(apps, schema_editor):
    Estado = apps.get_model("gestion_empleados", "EstadoPostulacion")
    for orden, nombre in enumerate(("Pendiente", "En revisión", "Prueba de Confiabilidad", "Aprobado", "No aprobado"), 1): Estado.objects.get_or_create(nombre=nombre, defaults={"orden": orden})
    Requisito = apps.get_model("gestion_empleados", "CatalogoRequisito")
    codigos = [str(x) for x in range(1, 11)] + ["10.1", "10.2"] + [str(x) for x in range(11, 20)]
    for orden, codigo in enumerate(codigos, 1):
        Requisito.objects.get_or_create(codigo=codigo, defaults={"descripcion": f"Requisito {codigo} del formulario FR-029-DRH-CRSP-UE-A01-2024", "fase": "POST_AVAL" if codigo in {"15", "16", "17", "18", "19"} else "PRE_AVAL", "orden": orden})



class Migration(migrations.Migration):
    dependencies = [("gestion_empleados", "0001_initial"), ("empleados_app", "0005_contrato_estado_contrato_fecha_registro_rescision_and_more"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="EstadoPostulacion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("nombre", models.CharField(max_length=60, unique=True)), ("orden", models.PositiveSmallIntegerField(default=0)), ("activo", models.BooleanField(default=True))], options={"ordering": ("orden", "nombre")}),
        migrations.CreateModel(name="CatalogoRequisito", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("codigo", models.CharField(max_length=10, unique=True)), ("descripcion", models.TextField()), ("fase", models.CharField(choices=[("PRE_AVAL", "Pre-aval"), ("POST_AVAL", "Post-aval")], max_length=10)), ("obligatorio", models.BooleanField(default=True)), ("orden", models.PositiveSmallIntegerField()), ("activo", models.BooleanField(default=True))], options={"ordering": ("fase", "orden")}),
        migrations.CreateModel(name="Postulante", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("cui", models.CharField(max_length=15, unique=True, verbose_name="DPI / CUI")), ("nombres", models.CharField(max_length=100)), ("apellidos", models.CharField(max_length=100)), ("programa_area", models.CharField(max_length=180, verbose_name="programa / área propuesta")), ("fecha_solicitud", models.DateField(default=datetime.date.today)), ("ficha_tecnica", models.FileField(blank=True, upload_to="gestion_empleados/fichas_tecnicas/")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("empleado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="postulaciones", to="empleados_app.empleado")), ("estado_tdr", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="postulantes", to="gestion_empleados.estadopostulacion")), ("responsable", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="postulantes_responsable", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-created_at",), "permissions": [("continue_postulante", "Puede continuar proceso de postulante")]}),
        migrations.CreateModel(name="PerfilRRHHEmpleado", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("nit", models.CharField(blank=True, max_length=20)), ("pertenencia_sociolinguistica", models.CharField(blank=True, max_length=100)), ("discapacidad", models.CharField(blank=True, max_length=180)), ("municipio_domicilio", models.CharField(blank=True, max_length=100)), ("departamento_domicilio", models.CharField(blank=True, max_length=100)), ("correo_personal", models.EmailField(blank=True, max_length=254)), ("profesion", models.CharField(blank=True, max_length=150)), ("numero_colegiado", models.CharField(blank=True, max_length=40)), ("cuenta_banrural", models.CharField(blank=True, max_length=40)), ("updated_at", models.DateTimeField(auto_now=True)), ("empleado", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="perfil_rrhh", to="empleados_app.empleado"))]),
        migrations.CreateModel(name="InformacionContrato029", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("puesto_funcional", models.CharField(blank=True, max_length=180)), ("puesto_nominal", models.CharField(blank=True, max_length=180)), ("tdr", models.FileField(blank=True, upload_to="gestion_empleados/tdr/")), ("codigo_guatenominas", models.CharField(blank=True, max_length=50)), ("correo_institucional", models.EmailField(blank=True, max_length=254)), ("dependencia", models.CharField(blank=True, max_length=180)), ("departamento", models.CharField(blank=True, max_length=180)), ("seccion", models.CharField(blank=True, max_length=180)), ("programa_area", models.CharField(blank=True, max_length=180)), ("departamento_servicios", models.CharField(blank=True, max_length=180)), ("numero_contrato", models.CharField(blank=True, db_index=True, max_length=50)), ("fecha_primera_contratacion", models.DateField(blank=True, null=True)), ("resolucion_aprobacion", models.CharField(blank=True, max_length=100)), ("fecha_resolucion", models.DateField(blank=True, null=True)), ("numero_fianza", models.CharField(blank=True, max_length=100)), ("honorarios_mensuales", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)), ("primer_pago", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)), ("honorarios_totales", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)), ("monto_total_contrato", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)), ("partida_presupuestaria", models.CharField(blank=True, max_length=100)), ("partida_repro", models.CharField(blank=True, max_length=100)), ("actividad", models.CharField(blank=True, max_length=180)), ("updated_at", models.DateTimeField(auto_now=True)), ("actualizado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos_029_actualizados", to=settings.AUTH_USER_MODEL)), ("contrato", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="informacion_029", to="empleados_app.contrato"))]),
        migrations.CreateModel(name="EvaluacionExpediente", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("completo", models.BooleanField(default=False)), ("fecha_completado", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("completado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="evaluaciones_completadas", to=settings.AUTH_USER_MODEL)), ("postulante", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="evaluacion", to="gestion_empleados.postulante"))]),
        migrations.CreateModel(name="HistorialEstadoPostulante", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("observacion", models.TextField(blank=True)), ("fecha", models.DateTimeField(auto_now_add=True)), ("estado_anterior", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="historial_origen", to="gestion_empleados.estadopostulacion")), ("estado_nuevo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="historial_destino", to="gestion_empleados.estadopostulacion")), ("postulante", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historial_estados", to="gestion_empleados.postulante")), ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))], options={"ordering": ("-fecha",)}),
        migrations.CreateModel(name="DetalleEvaluacionRequisito", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("cumple", models.BooleanField(default=False)), ("observacion", models.TextField(blank=True)), ("fecha_revision", models.DateTimeField(blank=True, null=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("evaluacion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="detalles", to="gestion_empleados.evaluacionexpediente")), ("requisito", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="gestion_empleados.catalogorequisito")), ("revisado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name="detalleevaluacionrequisito", constraint=models.UniqueConstraint(fields=("evaluacion", "requisito"), name="evaluacion_requisito_unico")),
        migrations.CreateModel(name="HistorialRevisionRequisito", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("cumple", models.BooleanField()), ("observacion", models.TextField(blank=True)), ("fecha", models.DateTimeField(auto_now_add=True)), ("detalle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historial", to="gestion_empleados.detalleevaluacionrequisito")), ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))]),
        migrations.RunPython(seed_catalogos, migrations.RunPython.noop),
    ]
