import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cargar_catalogos(apps, schema_editor):
    EstadoControl = apps.get_model("gestion_empleados", "EstadoControlMensual")
    for orden, (codigo, nombre, completo) in enumerate((
        ("pendiente", "Pendiente", False), ("recibido", "Recibido", False),
        ("en-revision", "En revisión", False), ("con-observaciones", "Con observaciones", False),
        ("completo", "Completo", True), ("validado", "Validado", True),
    ), 1):
        EstadoControl.objects.get_or_create(codigo=codigo, defaults={"nombre": nombre, "orden": orden, "es_completo": completo})
    Tipo = apps.get_model("gestion_empleados", "TipoDocumento")
    for codigo, nombre in (("entregable", "Entregable"), ("informe-mensual", "Informe mensual"), ("factura-fel", "Factura FEL"), ("reporte-actividades", "Reporte de actividades")):
        Tipo.objects.get_or_create(codigo=codigo, defaults={"nombre": nombre, "obligatorio": True, "aplica_control_mensual": True})
    EstadoCaso = apps.get_model("gestion_empleados", "EstadoCasoJudicial")
    for orden, (codigo, nombre, cerrado) in enumerate((("abierto", "Abierto", False), ("seguimiento", "En seguimiento", False), ("suspendido", "Suspendido", False), ("cerrado", "Cerrado", True), ("archivado", "Archivado", True)), 1):
        EstadoCaso.objects.get_or_create(codigo=codigo, defaults={"nombre": nombre, "cerrado": cerrado, "orden": orden})


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("empleados_app", "0005_contrato_estado_contrato_fecha_registro_rescision_and_more"),
        ("gestion_empleados", "0002_fases_funcionales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AlterModelOptions(name="expedienteempleado", options={"verbose_name": "expediente de empleado", "verbose_name_plural": "expedientes de empleados", "permissions": [("view_gestion_empleados", "Puede ver Gestión de Empleados"), ("manage_preselection", "Puede gestionar preselección"), ("review_employee_files", "Puede revisar expedientes"), ("edit_employee_record", "Puede editar la ficha del empleado"), ("manage_employee_contracts", "Puede gestionar contratos"), ("rescind_employee_contracts", "Puede rescindir contratos"), ("view_contract_information", "Puede consultar información contractual"), ("view_personnel_management", "Puede ver gestión de personal"), ("manage_monthly_deliverables", "Puede gestionar entregables mensuales"), ("validate_monthly_deliverables", "Puede validar entregables mensuales"), ("ver_casos", "Puede ver casos judiciales"), ("crear_casos", "Puede crear casos judiciales"), ("editar_casos", "Puede editar casos judiciales"), ("cerrar_casos", "Puede cerrar o archivar casos judiciales")]}),
        migrations.CreateModel(name="EstadoControlMensual", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("nombre", models.CharField(max_length=60, unique=True)), ("codigo", models.SlugField(max_length=30, unique=True)), ("orden", models.PositiveSmallIntegerField(default=0)), ("es_completo", models.BooleanField(default=False)), ("activo", models.BooleanField(default=True))], options={"ordering": ("orden", "nombre")}),
        migrations.CreateModel(name="TipoDocumento", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("codigo", models.SlugField(max_length=50, unique=True)), ("nombre", models.CharField(max_length=120)), ("obligatorio", models.BooleanField(default=False)), ("aplica_control_mensual", models.BooleanField(default=False)), ("activo", models.BooleanField(default=True))]),
        migrations.CreateModel(name="EstadoCasoJudicial", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("nombre", models.CharField(max_length=60, unique=True)), ("codigo", models.SlugField(max_length=30, unique=True)), ("cerrado", models.BooleanField(default=False)), ("orden", models.PositiveSmallIntegerField(default=0))], options={"ordering": ("orden", "nombre")}),
        migrations.CreateModel(name="ControlMensualContrato", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("mes", models.PositiveSmallIntegerField()), ("anio", models.PositiveSmallIntegerField()), ("fecha_recepcion", models.DateField(blank=True, null=True)), ("observaciones", models.TextField(blank=True)), ("fecha_revision", models.DateTimeField(blank=True, null=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("contrato", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="controles_mensuales", to="empleados_app.contrato")), ("estado", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="controles", to="gestion_empleados.estadocontrolmensual")), ("responsable", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="controles_mensuales_responsable", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-anio", "-mes")}),
        migrations.AddConstraint(model_name="controlmensualcontrato", constraint=models.UniqueConstraint(fields=("contrato", "mes", "anio"), name="control_mensual_periodo_unico")),
        migrations.AddConstraint(model_name="controlmensualcontrato", constraint=models.CheckConstraint(condition=models.Q(("mes__gte", 1), ("mes__lte", 12)), name="control_mes_valido")),
        migrations.CreateModel(name="DocumentoGestion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("archivo", models.FileField(upload_to="gestion_empleados/documentos/%Y/%m/")), ("estado", models.CharField(choices=[("recibido", "Recibido"), ("revision", "En revisión"), ("observado", "Observado"), ("validado", "Validado")], default="recibido", max_length=12)), ("observacion", models.TextField(blank=True)), ("fecha", models.DateTimeField(auto_now_add=True)), ("object_id", models.PositiveBigIntegerField()), ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype")), ("tipo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documentos", to="gestion_empleados.tipodocumento")), ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documentos_gestion_cargados", to=settings.AUTH_USER_MODEL))]),
        migrations.AddIndex(model_name="documentogestion", index=models.Index(fields=["content_type", "object_id"], name="documento_expediente_idx")),
        migrations.CreateModel(name="CasoJudicial", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("numero_caso", models.CharField(max_length=80, unique=True)), ("tipo", models.CharField(max_length=100)), ("organo_competente", models.CharField(max_length=180)), ("fecha_inicio", models.DateField()), ("fecha_ultima_actuacion", models.DateField(blank=True, null=True)), ("observaciones", models.TextField(blank=True)), ("fecha_creacion", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("actualizado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="casos_judiciales_actualizados", to=settings.AUTH_USER_MODEL)), ("contrato", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="casos_judiciales", to="empleados_app.contrato")), ("creado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="casos_judiciales_creados", to=settings.AUTH_USER_MODEL)), ("empleado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="casos_judiciales", to="empleados_app.empleado")), ("estado", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="casos", to="gestion_empleados.estadocasojudicial")), ("responsable", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="casos_judiciales_responsable", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-fecha_inicio",)}),
        migrations.CreateModel(name="CasoActuacion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("fecha", models.DateField(default=datetime.date.today)), ("tipo_actuacion", models.CharField(max_length=120)), ("detalle", models.TextField()), ("documento", models.FileField(blank=True, upload_to="gestion_empleados/casos/%Y/%m/")), ("created_at", models.DateTimeField(auto_now_add=True)), ("caso", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="actuaciones", to="gestion_empleados.casojudicial")), ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="actuaciones_judiciales", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-fecha", "-created_at")}),
        migrations.CreateModel(name="RegistroAuditoria", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("accion", models.CharField(max_length=80)), ("detalle", models.TextField(blank=True)), ("fecha", models.DateTimeField(auto_now_add=True)), ("object_id", models.PositiveBigIntegerField()), ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contenttypes.contenttype")), ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="auditoria_gestion_empleados", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-fecha",)}),
        migrations.AddIndex(model_name="registroauditoria", index=models.Index(fields=["content_type", "object_id"], name="auditoria_objeto_idx")),
        migrations.RunPython(cargar_catalogos, migrations.RunPython.noop),
    ]
