# Generated by Django 5.1.4 on 2025-11-12 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainsumo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FraseMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=500)),
                ('personaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renglon', models.IntegerField()),
                ('codigo_insumo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=500)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('nombre_presentacion', models.CharField(max_length=500)),
                ('cantidad_unidad_presentacion', models.CharField(max_length=100)),
                ('codigo_presentacion', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_contacto', models.CharField(choices=[('telefono', 'Telefono'), ('wahtsapp', 'WhatsApp'), ('personal ', 'Personal'), ('correo', 'Correo')], default='telefono', max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=100)),
                ('detalle_problema', models.TextField(blank=True)),
                ('solucion_problema', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado'), ('pendiente', 'Pendiente')], default='abierto', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='alta', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets_app.oficina')),
                ('tecnico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('tipo_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets_app.tipoequipo')),
            ],
        ),
    ]
