# Generated by Django 5.1.4 on 2025-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=100)),
                ('via_contacto', models.CharField(max_length=100)),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('problema', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=100)),
                ('detalle_problema', models.TextField()),
                ('tecnico_asignado', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado'), ('pendiente', 'Pendiente')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
