# Generated by Django 5.1.4 on 2025-11-13 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion', models.CharField(choices=[('scompras', 'SICOMPRA'), ('almacen', 'ALMACÉN'), ('empleados', 'EMPLEADOS'), ('afiliados', 'AFILIADOS'), ('rrhh', 'RECURSOS HUMANOS')], max_length=50)),
                ('tiene_acceso', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'aplicacion')},
            },
        ),
    ]
