# Generated by Django 5.1.4 on 2025-11-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0002_appacceso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppAcceso',
        ),
    ]
