# Generated by Django 5.1.4 on 2025-01-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0002_alter_ticket_tecnico_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solucion_problema',
            field=models.TextField(default=55),
            preserve_default=False,
        ),
    ]
