# Generated by Django 5.1.4 on 2025-01-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0003_ticket_solucion_problema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='correo',
            field=models.EmailField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='telefono',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
