# Generated by Django 5.1.4 on 2025-01-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0004_ticket_correo_ticket_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='oficina',
            field=models.CharField(choices=[('coordinacion_general', 'Coordinación General'), ('departamento_administrativo_financiero', 'Departamento Administrativo Financiero'), ('seccion_presupuesto', 'Sección de Presupuesto'), ('seccion_tesoreria_compras', 'Sección de Tesorería y Compras'), ('seccion_contabilidad', 'Sección de Contabilidad'), ('seccion_almacen_inventario', 'Sección de Almacén e Inventario'), ('seccion_apoyo_logistico', 'Sección de Apoyo Logístico'), ('seccion_recursos_humanos', 'Sección de Recursos Humanos'), ('departamento_planificacion_estrategica', 'Departamento de Planificación Estratégica y Gestión por Resultados'), ('seccion_cooperacion', 'Sección de Cooperación'), ('seccion_organizacion_metodos', 'Sección Organización y Métodos'), ('seccion_comunicacion_social', 'Sección de Comunicación Social'), ('departamento_prevencion_violencia_juvenil', 'Departamento de Organización para la Prevención de la Violencia Juvenil'), ('seccion_participacion_juvenil', 'Sección Participación y Organización Juvenil'), ('seccion_escuelas_seguros', 'Sección Escuelas Seguras'), ('seccion_apoyo_servicio_civico', 'Sección Apoyo al Servicio Cívico'), ('departamento_organizacion_comunitaria', 'Departamento de Organización Comunitaria para la Prevención'), ('seccion_organizacion_metropolitana', 'Sección de Organización Metropolitana'), ('seccion_organizacion_departamental', 'Sección de Organización Departamental'), ('seccion_genero_multiculturalidad', 'Sección de Género y Multiculturalidad'), ('seccion_prevencion_post_penitenciaria', 'Sección de Prevención Post-Penitenciaria'), ('departamento_capacitacion_desarrollo', 'Departamento de Capacitación y Desarrollo Institucional'), ('seccion_formacion_capacitacion', 'Sección de Formación y Capacitación'), ('seccion_desarrollo_institucional', 'Sección de Desarrollo Institucional'), ('seccion_produccion_materiales', 'Sección de Producción de Materiales'), ('departamento_analisis_investigacion', 'Departamento de Análisis e Investigación Socio-Delictual'), ('seccion_investigacion_monitoreo', 'Sección Investigación y Monitoreo'), ('seccion_analisis_estadistica', 'Sección Análisis y Estadística'), ('seccion_estudios_socio_delictuales', 'Sección de Estudios Socio-Delictuales'), ('seccion_cartografia_informacion_geografica', 'Sección de Cartografía e Información Geográfica'), ('seccion_asesoria_juridica', 'Sección de Asesoría Jurídica')], max_length=100),
        ),
    ]
