# Generated by Django 5.1.4 on 2025-01-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0005_alter_ticket_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo_equipo',
            field=models.CharField(choices=[('internet_red', 'Internet o Red'), ('computadora', 'Computadora'), ('laptop', 'Laptop'), ('telefono', 'Teléfono'), ('impresora', 'Impresora'), ('canonera', 'Cañonera'), ('ups', 'UPS'), ('correo_electronico', 'Correo Electrónico'), ('dominio', 'Dominio'), ('camaras_seguridad', 'Cámaras de Seguridad'), ('televisores', 'Televisores'), ('gafetes', 'Gafetes'), ('biometrico', 'Biométrico'), ('plotter', 'Plotter'), ('aplicaciones', 'Aplicaciones'), ('antivirus', 'Antivirus'), ('firewall', 'Firewall'), ('servidores', 'Servidores'), ('datacenter_central', 'Datacenter Central'), ('isla_norte', 'Isla Norte'), ('isla_sur', 'Isla Sur'), ('isla_2do_nivel', 'Isla 2do Nivel'), ('isla_sotano', 'Isla Sótano'), ('almacenamiento', 'Almacenamiento'), ('varios', 'Varios'), ('pagina_web', 'Página Web'), ('software', 'Software'), ('escaner', 'Escáner'), ('backup', 'Backup'), ('camaras', 'Cámaras'), ('quema_discos', 'Quema de Discos'), ('cableado', 'Cableado'), ('gestion_firma_electronica', 'Gestión Firma Electrónica'), ('validacion_firma_electronica', 'Validación para Firma Electrónica')], max_length=100),
        ),
    ]
