# Generated by Django 5.1.4 on 2025-01-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0008_oficina_alter_ticket_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='alta', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='via_contacto',
            field=models.CharField(choices=[('telefono', 'Telefono'), ('wahtsapp', 'WhatsApp'), ('personal ', 'Personal'), ('correo', 'Correo')], default='telefono', max_length=100),
        ),
    ]
