# Generated by Django 5.1.4 on 2025-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0010_alter_ticket_correo_alter_ticket_detalle_problema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=500)),
                ('personaje', models.CharField(max_length=100)),
            ],
        ),
    ]
