# Generated by Django 5.1.4 on 2025-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0011_frasemotivacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renglon', models.IntegerField()),
                ('codigo_insumo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('nombre_presentacion', models.CharField(max_length=255)),
                ('cantidad_unidad_presentacion', models.CharField(max_length=100)),
                ('codigo_presentacion', models.CharField(max_length=100)),
            ],
        ),
    ]
