# Generated by Django 5.1.4 on 2025-05-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0013_alter_insumo_nombre_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
