# Generated by Django 5.1.4 on 2025-05-06 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0014_alter_insumo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
