# Generated by Django 5.1.4 on 2025-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0015_insumo_fecha_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='fechainsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainsumo', models.DateField()),
            ],
        ),
    ]
