# Generated by Django 5.1.4 on 2025-06-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0012_fechainsumo_insumo'),
        ('tickets_app', '0016_fechainsumo'),
    ]

    operations = [
    ]
