# Generated by Django 5.1.4 on 2025-11-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0003_delete_appacceso'),
        ('tickets_app', '0017_merge_0012_fechainsumo_insumo_0016_fechainsumo'),
    ]

    operations = [
    ]
