# Generated by Django 5.1.4 on 2025-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/', verbose_name='Logotipo')),
                ('logotipo2', models.ImageField(blank=True, null=True, upload_to='logotipos2/', verbose_name='Logotipo2')),
            ],
        ),
    ]
