# Generated by Django 5.1.4 on 2025-02-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0002_configuraciongeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dcargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
