# Generated by Django 5.1.4 on 2025-11-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0002_alter_empleado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBasicosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)'), ('union', 'Unión de hecho')], max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_etnico', models.CharField(blank=True, max_length=50, null=True)),
                ('idiomas', models.CharField(blank=True, help_text='Ejemplo: Español (Nativo), Inglés (Básico)', max_length=200, null=True)),
                ('direccion_residencia', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono_personal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('persona_contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_basicos', to='empleados_app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademicaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('basicos', 'Básicos'), ('diversificado', 'Diversificado'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('diplomado', 'Diplomado'), ('certificado', 'Certificado'), ('otro', 'Otro')], max_length=20)),
                ('titulo_obtenido', models.CharField(blank=True, max_length=150, null=True)),
                ('centro_estudio', models.CharField(max_length=150)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='empleados_app.empleado')),
            ],
        ),
    ]
