# Generated by Django 5.1.4 on 2025-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0003_empleado_dcargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dcargo2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
