# Generated by Django 5.1.4 on 2025-11-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0003_datosbasicosempleado_formacionacademicaempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbasicosempleado',
            name='grupo_etnico',
            field=models.CharField(blank=True, choices=[('maya', 'Maya'), ('xinca', 'Xinca'), ('garifuna', 'Garífuna'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
