# Generated by Django 5.1.4 on 2026-04-16 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def establecer_estado_inicial(apps, schema_editor):
    Contrato = apps.get_model("empleados_app", "Contrato")
    Contrato.objects.filter(activo=True).update(estado="activo")
    Contrato.objects.filter(activo=False).update(estado="vencido")


class Migration(migrations.Migration):

    dependencies = [
        ("empleados_app", "0004_alter_datosbasicosempleado_grupo_etnico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("rescindido", "Rescindido"),
                    ("vencido", "Vencido"),
                ],
                default="activo",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="fecha_registro_rescision",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="fecha_rescision",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="motivo_rescision",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="observaciones_rescision",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="rescindido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_rescindidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(establecer_estado_inicial, migrations.RunPython.noop),
    ]
