# Generated by Django 5.1.4 on 2025-09-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0005_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contrato',
        ),
    ]
