# Generated by Django 5.1.4 on 2025-09-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0006_remove_contrato_activo_remove_contrato_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
