# Generated by Django 5.1.4 on 2025-10-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0007_contrato_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='contrato',
            name='renglon',
            field=models.CharField(choices=[('029', '029'), ('021', '021')], default='029', max_length=3),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipocontrato',
            field=models.CharField(default='029', max_length=100),
            preserve_default=False,
        ),
    ]
