# Generated by Django 5.1.4 on 2025-10-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0008_remove_empleado_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='tipocontrato',
            new_name='tipo_contrato',
        ),
    ]
