# Generated by Django 5.1.4 on 2025-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0009_rename_tipocontrato_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('Servicios Técnicos', 'Servicios Técnicos'), ('Servicios Profesionales', 'Servicios Profesionales'), ('Personal Permanente', 'Personal Permanente')], default='Servicios Técnicos', max_length=50),
        ),
    ]
