# Generated by Django 5.1.4 on 2025-10-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0011_puesto_sede_contrato_puesto_contrato_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='sede',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='empleados_app.sede'),
            preserve_default=False,
        ),
    ]
