# Generated by Django 5.1.4 on 2025-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0012_puesto_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='renglon',
            field=models.CharField(choices=[('029', '029'), ('021', '021'), ('022', '022')], default='029', max_length=3),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
