"""
Django settings for upcv_app project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-av1$b$x&1_-3naz=js=74&=(s&5ph00m4t1_c&9190ar3cm%ok'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.93.114', 'localhost', '127.0.0.1', '181.174.112.19',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'scompras_app.apps.scomprasAppConfig',  # ✅ solo esta línea
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'upcv_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'scompras_app.context_processors.frase_del_dia',  # Agregar el context processor personalizado
                'scompras_app.context_processors.grupo_usuario',
                'scompras_app.context_processors.datos_institucion',
                'scompras_app.context_processors.media_server_tickets',
                'scompras_app.context_processors.permisos_configuracion',
                'scompras_app.context_processors.scompras_roles',

            ],
        },
    },
]

WSGI_APPLICATION = 'upcv_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Tickets',  # Cambia esto por el nombre de tu base de datos
        'USER': 'postgres',
        'PASSWORD': 'Jrodash2*',  # La contraseña que configuraste
        'HOST': 'localhost',
        'PORT': '5432',  # O el puerto que hayas configurado
    },
    'tickets_db': {  # Nueva conexión de solo lectura
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Tickets',
        'USER': 'postgres',
        'PASSWORD': 'Jrodash2*',
        'HOST': 'localhost',
        'PORT': '5432',
},
      }

AUTHENTICATION_BACKENDS = [
    'scompras_app.backends.TicketsAuthBackend',  # Primero busca en la BD de Tickets
    'django.contrib.auth.backends.ModelBackend',  # Luego en la local (respaldo)
]

DATABASE_ROUTERS = ['scompras_app.dbrouters.TicketsRouter']




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-gt'

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

import os
# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # Usa '/static/' para la URL de acceso

# Esta es la carpeta donde durante el desarrollo puedes tener tus archivos estáticos personalizados
STATICFILES_DIRS = [BASE_DIR / 'static']  # Asegúrate de tener una carpeta 'static' con tus archivos

# En producción, `collectstatic` moverá los archivos estáticos a esta carpeta
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración para manejar archivos de medios
MEDIA_URL = '/media/'  # La URL pública donde los archivos de medios serán accesibles
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # El directorio donde se scomprasan los archivos subidos

# Servidor donde corre TICKETS
MEDIA_SERVER_TICKETS = "http://127.0.0.1:8000"

LOGIN_URL = '/no-autorizado/'  # o una ruta válida a la que redirigir

LOGOUT_ON_PASSWORD_CHANGE = True  # si usas algún middleware de seguridad extendido


EMAIL_BACKEND = 'scompras_app.email_backend.CustomEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'informatica@upcv.gob.gt'  
EMAIL_HOST_PASSWORD = 'xtdj nvwz ymyw lqyr'  

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
